version: "3.3"

services:
  # Nginx
  web:
    container_name: nginx
    image: docker.io/nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./proyectos/:/var/www/
      - ./nginx.php-fpm.conf:/etc/nginx/nginx.conf:ro
    links:
      - php-fpm

  # Configuración de php
  php-fpm:
    container_name: php
    build: .
    volumes:
      - ./proyectos:/var/www/html

  #MariaDB
  db:
    container_name: mariadb
    image: docker.io/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: ejemplo
      MARIADB_USER: usuario
      MARIADB_PASSWORD: usuario
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
